# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/260805_AIGIS_inseok/zyboproject_inseok/.Xil/Vivado-9772-DESKTOP-7CFQ9ND/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z020clg400-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv {
      D:/260805_AIGIS_inseok/zyboproject_inseok/rtl/aes_gcm/aes128_encrypt_block.sv
      D:/260805_AIGIS_inseok/zyboproject_inseok/rtl/aes_gcm/aes128_gcm_decrypt_block.sv
      D:/260805_AIGIS_inseok/zyboproject_inseok/rtl/aes_gcm/aes128_gcm_decrypt_ip.sv
      D:/260805_AIGIS_inseok/zyboproject_inseok/rtl/aes_gcm/aes128_gcm_encrypt_block.sv
      D:/260805_AIGIS_inseok/zyboproject_inseok/rtl/aes_gcm/aes128_gcm_encrypt_ip.sv
      D:/260805_AIGIS_inseok/zyboproject_inseok/rtl/aes_gcm/aes_pkg.sv
      D:/260805_AIGIS_inseok/zyboproject_inseok/rtl/aes_gcm/aes128_key_schedule.sv
      D:/260805_AIGIS_inseok/zyboproject_inseok/rtl/aes_gcm/aes128_pipelined_encrypt_core.sv
      D:/260805_AIGIS_inseok/zyboproject_inseok/rtl/aes_gcm/aes_add_round_key.sv
      D:/260805_AIGIS_inseok/zyboproject_inseok/rtl/aes_gcm/aes_encrypt_round.sv
      D:/260805_AIGIS_inseok/zyboproject_inseok/rtl/secure/aes_gcm_decrypt_packet.sv
      D:/260805_AIGIS_inseok/zyboproject_inseok/rtl/secure/aes_gcm_encrypt_packet.sv
      D:/260805_AIGIS_inseok/zyboproject_inseok/rtl/aes_gcm/aes_gcm_ghash.sv
      D:/260805_AIGIS_inseok/zyboproject_inseok/rtl/aes_gcm/aes_mix_columns.sv
      D:/260805_AIGIS_inseok/zyboproject_inseok/rtl/aes_gcm/aes_shift_rows.sv
      D:/260805_AIGIS_inseok/zyboproject_inseok/rtl/aes_gcm/aes_sub_bytes.sv
      D:/260805_AIGIS_inseok/zyboproject_inseok/rtl/legacy/pxc_sync_fifo.sv
      D:/260805_AIGIS_inseok/zyboproject_inseok/rtl/secure/secure_uart_frame_rx.sv
      D:/260805_AIGIS_inseok/zyboproject_inseok/rtl/secure/secure_uart_frame_tx.sv
      D:/260805_AIGIS_inseok/zyboproject_inseok/rtl/legacy/spi_master.sv
      D:/260805_AIGIS_inseok/zyboproject_inseok/rtl/legacy/spi_slave.sv
      D:/260805_AIGIS_inseok/zyboproject_inseok/rtl/legacy/uart_rx.sv
      D:/260805_AIGIS_inseok/zyboproject_inseok/rtl/legacy/uart_tx.sv
      D:/260805_AIGIS_inseok/zyboproject_inseok/rtl/secure/zybo_session_manager.sv
      D:/260805_AIGIS_inseok/zyboproject_inseok/rtl/secure/zybo_secure_control_unit_v2.sv
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList D:/260805_AIGIS_inseok/zyboproject_inseok/.Xil/Vivado-9772-DESKTOP-7CFQ9ND/realtime/zybo_secure_control_unit_v2_synth.xdc
    rt::sdcChecksum
    set rt::top zybo_secure_control_unit_v2
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {D:/260805_AIGIS_inseok/zyboproject_inseok/vivado_jetson_secure/zybo_secure_jetson.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "D:/260805_AIGIS_inseok/zyboproject_inseok/.Xil/Vivado-9772-DESKTOP-7CFQ9ND/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
