# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/260807_AIGIS_inseok/basys3project_inseok_jeong/vivado/basys3_secure_v2.runs/synth_1/basys3_secure_rack_control.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/260807_AIGIS_inseok/basys3project_inseok_jeong/vivado/basys3_secure_v2.cache/wt [current_project]
set_property parent.project_path D:/260807_AIGIS_inseok/basys3project_inseok_jeong/vivado/basys3_secure_v2.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo d:/260807_AIGIS_inseok/basys3project_inseok_jeong/vivado/basys3_secure_v2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv {
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/legacy/vision/RTL/CAM_Set/CAM_Set.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/legacy/vision/RTL/UI_Set/Drone_detector/Drone_Classification_Color.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/legacy/vision/RTL/LED_Set/led_zone_pkg.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/legacy/vision/RTL/Frame_Set/Frame_Set.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/legacy/vision/RTL/LED_Set/LED_Set.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/legacy/vision/RTL/CAM_Set/OV7670MemController.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/legacy/vision/RTL/CAM_Set/OV7670_Controller.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/legacy/vision/RTL/CAM_Set/OV7670_attribute_setting.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/legacy/vision/RTL/CAM_Set/UpScaleImgReader.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/legacy/vision/RTL/VGA_Decoder.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/aes_gcm/aes128_encrypt_block.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/aes_gcm/aes128_gcm_decrypt_block.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/aes_gcm/aes128_gcm_decrypt_ip.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/aes_gcm/aes128_gcm_encrypt_block.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/aes_gcm/aes128_gcm_encrypt_ip.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/aes_gcm/aes_pkg.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/aes_gcm/aes128_key_schedule.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/aes_gcm/aes128_pipelined_encrypt_core.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/aes_gcm/aes_add_round_key.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/aes_gcm/aes_encrypt_round.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/secure/aes_gcm_decrypt_packet.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/secure/aes_gcm_encrypt_packet.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/aes_gcm/aes_gcm_ghash.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/aes_gcm/aes_mix_columns.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/aes_gcm/aes_shift_rows.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/aes_gcm/aes_sub_bytes.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/legacy/fire_servo_controller.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/legacy/vision/RTL/CAM_Set/frameBuffer.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/legacy/vision/RTL/LED_Set/led_zone_monitor.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/legacy/rack_servo_controller.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/legacy/vision/RTL/CAM_Set/sccb_master.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/legacy/spi_slave.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/legacy/vision/RTL/LED_Set/status_packer.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/legacy/vision/RTL/LED_Set/unit_status.sv
  D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/secure/basys3_secure_rack_control.sv
}
read_verilog -library xil_defaultlib D:/260807_AIGIS_inseok/basys3project_inseok_jeong/rtl/legacy/dht11_controller.v
read_ip -quiet D:/260807_AIGIS_inseok/basys3project_inseok_jeong/vivado/basys3_secure_v2.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/260807_AIGIS_inseok/basys3project_inseok_jeong/vivado/basys3_secure_v2.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/260807_AIGIS_inseok/basys3project_inseok_jeong/vivado/basys3_secure_v2.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/260807_AIGIS_inseok/basys3project_inseok_jeong/vivado/basys3_secure_v2.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_late.xdc]
set_property used_in_implementation false [get_files -all d:/260807_AIGIS_inseok/basys3project_inseok_jeong/vivado/basys3_secure_v2.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/260807_AIGIS_inseok/basys3project_inseok_jeong/constraints/basys3_secure.xdc
set_property used_in_implementation false [get_files D:/260807_AIGIS_inseok/basys3project_inseok_jeong/constraints/basys3_secure.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top basys3_secure_rack_control -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef basys3_secure_rack_control.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file basys3_secure_rack_control_utilization_synth.rpt -pb basys3_secure_rack_control_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
