# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/260807_AIGIS_inseok/basys3project_inseok_jeong/constraints/basys3_secure.xdc

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: d:/260807_AIGIS_inseok/basys3project_inseok_jeong/vivado/basys3_secure_v2.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/260807_AIGIS_inseok/basys3project_inseok_jeong/vivado/basys3_secure_v2.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/260807_AIGIS_inseok/basys3project_inseok_jeong/vivado/basys3_secure_v2.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/260807_AIGIS_inseok/basys3project_inseok_jeong/vivado/basys3_secure_v2.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
